import { CreateInvestmentDto } from '../dtos/create-investment.dto';
import { InvestmentTypeEnum, InvestmentStatusEnum } from '@common/enums/investment.enum';

export const SEED_INVESTMENTS: CreateInvestmentDto[] = [
  // Apartments
  {
    title: '강남구 아파트 담보 대출',
    type: InvestmentTypeEnum.APARTMENT,
    rate: 8.5,
    period: 12,
    fundingGoal: 100000000,
    minInvestment: 1000000,
    borrowerType: '개인',
    status: InvestmentStatusEnum.FUNDING,
    badge: '인기',
    propertyAddress: '서울시 강남구 테헤란로 123',
    propertySize: '84㎡',
    buildYear: 2015,
    kbValuation: 650000000,
    currentLien: 300000000,
    ltv: 65,
  },
  {
    title: '서초동 빌라 담보 대출',
    type: InvestmentTypeEnum.APARTMENT,
    rate: 7.8,
    period: 18,
    fundingGoal: 80000000,
    minInvestment: 2000000,
    borrowerType: '개인',
    status: InvestmentStatusEnum.RECRUITING,
    badge: '신규',
    propertyAddress: '서울시 서초구 강남대로 456',
    propertySize: '120㎡',
    buildYear: 2010,
    kbValuation: 500000000,
    currentLien: 200000000,
    ltv: 60,
  },
  {
    title: '목동 재건축 아파트 대출',
    type: InvestmentTypeEnum.APARTMENT,
    rate: 9.2,
    period: 24,
    fundingGoal: 150000000,
    minInvestment: 5000000,
    borrowerType: '법인',
    status: InvestmentStatusEnum.ENDING_SOON,
    badge: '마감임박',
    propertyAddress: '서울시 양천구 목동로 789',
    propertySize: '156㎡',
    buildYear: 2005,
    kbValuation: 850000000,
    currentLien: 500000000,
    ltv: 70,
  },
  {
    title: '부산 해운대 신축 오피스텔',
    type: InvestmentTypeEnum.APARTMENT,
    rate: 8.0,
    period: 20,
    fundingGoal: 120000000,
    minInvestment: 3000000,
    borrowerType: '개인사업자',
    status: InvestmentStatusEnum.FUNDING,
    badge: '고수익',
    propertyAddress: '부산시 해운대구 우동 321',
    propertySize: '84㎡',
    buildYear: 2023,
    kbValuation: 680000000,
    currentLien: 350000000,
    ltv: 65,
  },

  // Credit Card receivables
  {
    title: '골프용품 쇼핑몰 신용카드 외상채권',
    type: InvestmentTypeEnum.CREDIT_CARD,
    rate: 9.5,
    period: 6,
    fundingGoal: 50000000,
    minInvestment: 1000000,
    borrowerType: '개인사업자',
    status: InvestmentStatusEnum.FUNDING,
    badge: '고수익',
    merchantName: 'Golf Mart Korea',
    merchantCategory: '스포츠용품',
    outstandingAmount: 48000000,
  },
  {
    title: '뷰티샵 체인 신용카드 외상채권',
    type: InvestmentTypeEnum.CREDIT_CARD,
    rate: 8.2,
    period: 9,
    fundingGoal: 40000000,
    minInvestment: 1000000,
    borrowerType: '개인사업자',
    status: InvestmentStatusEnum.FUNDING,
    merchantName: 'Beauty Plus Chain',
    merchantCategory: '미용',
    outstandingAmount: 35000000,
  },
  {
    title: '카페 프랜차이즈 신용카드 외상채권',
    type: InvestmentTypeEnum.CREDIT_CARD,
    rate: 7.5,
    period: 12,
    fundingGoal: 30000000,
    minInvestment: 500000,
    borrowerType: '법인',
    status: InvestmentStatusEnum.RECRUITING,
    badge: '신규',
    merchantName: 'Coffee House Corp',
    merchantCategory: '음식점',
    outstandingAmount: 28000000,
  },
  {
    title: '의류 수입업체 신용카드 외상채권',
    type: InvestmentTypeEnum.CREDIT_CARD,
    rate: 8.8,
    period: 8,
    fundingGoal: 60000000,
    minInvestment: 2000000,
    borrowerType: '개인사업자',
    status: InvestmentStatusEnum.ENDING_SOON,
    badge: '마감임박',
    merchantName: 'Fashion Import Co',
    merchantCategory: '의류',
    outstandingAmount: 58000000,
  },

  // Business Loans
  {
    title: 'IT 스타트업 성장 자금',
    type: InvestmentTypeEnum.BUSINESS_LOAN,
    rate: 8.8,
    period: 36,
    fundingGoal: 500000000,
    minInvestment: 10000000,
    borrowerType: '스타트업',
    status: InvestmentStatusEnum.RECRUITING,
    badge: '신규',
    businessName: 'TechStartup Inc',
    businessCategory: 'IT/소프트웨어',
    annualRevenue: 2000000000,
  },
  {
    title: '건설업 운영자금 대출',
    type: InvestmentTypeEnum.BUSINESS_LOAN,
    rate: 7.2,
    period: 24,
    fundingGoal: 800000000,
    minInvestment: 20000000,
    borrowerType: '법인',
    status: InvestmentStatusEnum.FUNDING,
    businessName: 'Construction Corp',
    businessCategory: '건설',
    annualRevenue: 5000000000,
  },
  {
    title: '제조업체 시설 투자 자금',
    type: InvestmentTypeEnum.BUSINESS_LOAN,
    rate: 7.8,
    period: 48,
    fundingGoal: 1000000000,
    minInvestment: 50000000,
    borrowerType: '법인',
    status: InvestmentStatusEnum.ENDING_SOON,
    badge: '고수익',
    businessName: 'Manufacturing Ltd',
    businessCategory: '제조',
    annualRevenue: 8000000000,
  },
  {
    title: '물류 창고업 운영자금',
    type: InvestmentTypeEnum.BUSINESS_LOAN,
    rate: 6.5,
    period: 30,
    fundingGoal: 400000000,
    minInvestment: 5000000,
    borrowerType: '법인',
    status: InvestmentStatusEnum.RECRUITING,
    businessName: 'Logistics Hub',
    businessCategory: '물류',
    annualRevenue: 3000000000,
  },
];
